### ISSUE TITLE
beastling cannot parse `tsv` files

### ISSUE THREAD

**Issue by Anaphory** [lmaurits/BEASTling#86]
I will need to parse `tsv` files, but there is no way to tell beastling that my data file is separated by `\t` and not by `,`. `UnicodeDictReader` does support other delimiters, but I don't see a reasonable way to expose the full `**kw` functionality of that class to the user, and it's likely overkill anyway, so I suggest doing it the same way that I have seen it in some clld importers:

Assume the format is comma-separated, unless the filename ends in `.tsv`. (This could also be done with `os.path.splitext()`, but I don't see what we would gain from that.) We could, of course, expose that switch to the config file, but I think I prefer this.

```
def load_data(filename, file_format=None, lang_column=None):
    if filename.endswith(".tsv"):
        delimiter = "\t"
    else:
        delimiter = ","
    if filename == 'stdin':
        filename = sys.stdin
    with UnicodeDictReader(filename, delimiter=delimiter) as reader:
        if file_format is None:
            file_format = 'cldf' if all(
                [f in reader.fieldnames for f in ("Language_ID", "Value")]) and any(
                    [f in reader.fieldnames for f in ("Feature_ID", "Parameter_ID")]
                ) else 'beastling'
        if file_format == 'cldf':
            data = load_cldf_data(reader)
        elif file_format == 'beastling':
            data = load_beastling_data(reader, lang_column, filename)
        else:
            raise ValueError("File format specification '{:}' not understood".format(
                file_format))
    return data
```

(Code includes fix for #82)

**Comment by xrotwang** [comment]
Hm. tsv to csv is just [an additional command](https://csvkit.readthedocs.io/en/0.9.1/scripts/csvcut.html)

```
csvcut -t your.name.tsv > your.name.csv
```

I'm not sure this should be the responsibility of beastling.

**Comment by Anaphory** [comment]
I'm not arguing it's hard to do with a single command, quite the opposite.

But since it's also nearly trivial for beastling, and given that tsv is one of the standard CLDF file formats, I think beastling should be able to read it.

If that argument does not hold against the Unix philosophy of beastling, that's fine!

**Comment by xrotwang** [comment]
But then again, beastling is a command line tool, so it may not be too much of a burden for the user. People also often use`.tab` als filename extension for tab-separated values, and some may choose the uppercase variants, ... The proper way - of course - would be an accompanying metadata file specifying the [csv dialect](https://www.w3.org/TR/tabular-metadata/#dialect-descriptions).

Given this context, I don't see much benefit from extending beastling functionality from just one default case (which is at least somewhat easy to document) to two, or some other ill-specified subsets of the whole range of possible scenarios.

**Comment by Anaphory** [comment]
Point.

**Comment by lmaurits** [comment]
Actually, I don't think this should have been closed so hastily.

It's true that BEASTling currently only exists as a CLI tool, and indeed it sports features designed to make it attractive to Unix geeks, like reading data from stdin and outputting to stdout.  However:
1. I am not opposed to other interfaces, including GUIs or web apps, existing in the future, especially if someone else wants to do the work!
2. Even as a CLI-only program, I would prefer to keep it as easy as possible for non-greybeards to use, while giving nice options to the greybeards where possible, as opposed to designing things around the assumption that everybody who uses it is a proficient command line user (which plenty of linguists aren't).

I do share Robert's concern that we don't want to open a can of worms where we try to support a large number of badly defined formats, do lots of tedious work aimed at this, and end up still not catching all cases.  That doesn't sound fun or productive.  However, Gereon's point about tabbed data being part of the CLDF standard is also very important.  I consider good CLDF support to be a priority feature for BEASTling.  If BEASTling and CLDF robustly work well together then it will encourage wider adoption of both of these things.

The current CLDF experimental draft says:

> The core data file may also be encoded in tsv, i.e. using the tab character as column separator. If so, this must be indicated by using .tsv as filename extension.

In light of this, my opinion is that if someone feeds BEASTling a tab-separated CLDF data file with a .tsv extension and BEASTling chokes on it, then BEASTling is in the wrong, because the CLDF definition explicitly says that this is permitted.  The only correct options are:
1. BEASTling stops claiming to support CLDF
2. BEASTling acquires the ability to smoothly handle these files
3. CLDF drops support for .tsv

Option 2 seems the best to me.

With regard to the "BEASTling" file format that is also supported (i.e. a generic rows-are-languages, columns-are-features .csv), can't we go a long way toward supporting variation in data file dialects with very little work by using Python's csv.Sniffer module?  I don't have a lot of experience using that, but I assume it's smart enough to detect comma vs tab delimiting.

I feel like the following is sensible: if somebody puts `file_format = cldf` in their config file, then they are explicitly volunteering to follow the CLDF standard, to the letter.  If their data filename ends in .csv, it had better be comma-delimited, and if it ends in .tsv, it had better be tab-delimited, and if they've got it wrong and BEASTling breaks then that is their fault and they need to read the standard again.  If they don't include `file_format = cldf`, then they're not explicitly volunteering for anything, and we should just use csv.Sniffer.  This is quick and easy for us to code, and it should cover the vast majority of real world cases.  If csv.Sniffer chokes then they are probably doing something quite silly (like mixing tabs and commas, or inconsistently using quotation marks to include commas in data), and we can rightly tell them to use a more sensible format, and point them toward CLDF.

I feel like this is a reasonable middle-ground between either wasting all of our time writing code trying to support unlimited silly variation in file formats, and placing too much burden on the user to precisely match exactly one very strict format.

**Comment by xrotwang** [comment]
You are right, Luke. I admit to having been a bit dishonest. Having lost the fight for csv-only with CLDF probably means I shouldn't push others to fight for my position :)

I haven't used `csv.Sniffer` either, but would guess it's good enough for the BEASTling use case. Ideally, though, there'd be a sniffer taking into account `dialect` descriptions in a metadata file as well. Requiring `pycldf`for this may be a bit too much for the rather simple BEASTling case.

**Comment by lmaurits** [comment]
I think I've fixed this now, as proposed above.  @Anaphory can you do a pull and test with your use case?

**Comment by Anaphory** [comment]
For the attached file (renamed to .txt for uploading), I get “Unknown Dialect”. There may be a good reason for that, and it's clld's fault, not beastling's, but it means this issue is not really resolved.

```
$ beastling reconstruct.ini
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/python/beastling/cli.py", line 102, in do_generate
    config.process()
  File "/home/gereon/python/beastling/configuration.py", line 372, in process
    self.instantiate_models()
  File "/home/gereon/python/beastling/configuration.py", line 745, in instantiate_models
    model = covarion.CovarionModel(config, self)
  File "/home/gereon/python/beastling/models/binary.py", line 10, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "/home/gereon/python/beastling/models/basemodel.py", line 38, in __init__
    self.data = load_data(self.data_filename, file_format=model_config.get("file_format",None), lang_column=model_config.get("language_column",None))
  File "/home/gereon/python/beastling/fileio/datareaders.py", line 38, in load_data
    with UnicodeDictReader(filename, dialect=dialect) as reader:
  File "/home/gereon/opt/lib/python3.5/site-packages/clldutils/dsv.py", line 135, in __enter__
    self.reader = csv.reader(self.f, **self.kw)
_csv.Error: unknown dialect
```

[romance_cognates.txt](https://github.com/lmaurits/BEASTling/files/513522/romance_cognates.txt)

**Comment by Anaphory** [comment]
Actually, before drawing any conclusions, I should probably check my files and versions.

**Comment by Anaphory** [comment]
Yep, it still holds with current BEASTling develop branch in a clean virtualenv:

```
(ve_bt) [gereon@veredus 86]$ beastling reconstruct.ini
Error encountered while parsing configuration file:
Traceback (most recent call last):
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/cli.py", line 102, in do_generate
    config.process()
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/configuration.py", line 372, in process
    self.instantiate_models()
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/configuration.py", line 745, in instantiate_models
    model = covarion.CovarionModel(config, self)
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/models/binary.py", line 10, in __init__
    BaseModel.__init__(self, model_config, global_config)
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/models/basemodel.py", line 38, in __init__
    self.data = load_data(self.data_filename, file_format=model_config.get("file_format",None), lang_column=model_config.get("language_column",None))
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/BEASTling/beastling/fileio/datareaders.py", line 38, in load_data
    with UnicodeDictReader(filename, dialect=dialect) as reader:
  File "/home/gereon/sideprojects/beasling_tests/ve_bt/lib/python3.5/site-packages/clldutils/dsv.py", line 135, in __enter__
    self.reader = csv.reader(self.f, **self.kw)
_csv.Error: unknown dialect
```

**Comment by Anaphory** [comment]
Ah.

> class csv.excel_tab
>     The excel_tab class defines the usual properties of an Excel-generated TAB-delimited file. It is registered with the dialect name 'excel-tab'.

The class is called `excel_tab`, but if we specify that dialect as string, it needs to be `excel-tab`.

**Comment by Anaphory** [comment]
It looks like `test` in `fileio_tests.py` should have picked on this issue of not being able to read `tsv` files, why didn't it?

**Comment by lmaurits** [comment]
Safe to close this now?

**Comment by Anaphory** [comment]
I assume so, but this time I submitted the fix, so I assumed for code-review-like reasons someone of you would eyeball it and then close this.

**Comment by lmaurits** [comment]
LGTM.
